#' Miasta
#'
#' @description Lista wszystkich miast w Polsce z informacją w jakim województwie leżą
#'
#' @param miasta lista
#'
#' @return Nazwa województwa i miasta
#' @export
#'
#' @examples
#' wojewodztwa

miasta = list(c(1, 'DOLNOŚLĄSKIE', 'Bolesławiec'),
            c(2, 'DOLNOŚLĄSKIE', 'Nowogrodziec'),
            c(3, 'DOLNOŚLĄSKIE', 'Bielawa'),
            c(4, 'DOLNOŚLĄSKIE', 'Dzierżoniów'),
            c(5, 'DOLNOŚLĄSKIE', 'Pieszyce'),
            c(6, 'DOLNOŚLĄSKIE', 'Piława Górna'),
            c(7, 'DOLNOŚLĄSKIE', 'Niemcza'),
            c(8, 'DOLNOŚLĄSKIE', 'Głogów'),
            c(9, 'DOLNOŚLĄSKIE', 'Góra'),
            c(10, 'DOLNOŚLĄSKIE', 'Wąsosz'),
            c(11, 'DOLNOŚLĄSKIE', 'Jawor'),
            c(12, 'DOLNOŚLĄSKIE', 'Bolków'),
            c(13, 'DOLNOŚLĄSKIE', 'Karpacz'),
            c(14, 'DOLNOŚLĄSKIE', 'Kowary'),
            c(15, 'DOLNOŚLĄSKIE', 'Piechowice'),
            c(16, 'DOLNOŚLĄSKIE', 'Szklarska Poręba'),
            c(17, 'DOLNOŚLĄSKIE', 'Kamienna Góra'),
            c(18, 'DOLNOŚLĄSKIE', 'Lubawka'),
            c(19, 'DOLNOŚLĄSKIE', 'Duszniki-Zdrój'),
            c(20, 'DOLNOŚLĄSKIE', 'Kłodzko'),
            c(21, 'DOLNOŚLĄSKIE', 'Kudowa-Zdrój'),
            c(22, 'DOLNOŚLĄSKIE', 'Nowa Ruda'),
            c(23, 'DOLNOŚLĄSKIE', 'Polanica-Zdrój'),
            c(24, 'DOLNOŚLĄSKIE', 'Bystrzyca Kłodzka'),
            c(25, 'DOLNOŚLĄSKIE', 'Lądek-Zdrój'),
            c(26, 'DOLNOŚLĄSKIE', 'Międzylesie'),
            c(27, 'DOLNOŚLĄSKIE', 'Radków'),
            c(28, 'DOLNOŚLĄSKIE', 'Stronie Śląskie'),
            c(29, 'DOLNOŚLĄSKIE', 'Szczytna'),
            c(30, 'DOLNOŚLĄSKIE', 'Chojnów'),
            c(31, 'DOLNOŚLĄSKIE', 'Prochowice'),
            c(32, 'DOLNOŚLĄSKIE', 'Lubań'),
            c(33, 'DOLNOŚLĄSKIE', 'Świeradów-Zdrój'),
            c(34, 'DOLNOŚLĄSKIE', 'Leśna'),
            c(35, 'DOLNOŚLĄSKIE', 'Olszyna'),
            c(36, 'DOLNOŚLĄSKIE', 'Lubin'),
            c(37, 'DOLNOŚLĄSKIE', 'Ścinawa'),
            c(38, 'DOLNOŚLĄSKIE', 'Gryfów Śląski'),
            c(39, 'DOLNOŚLĄSKIE', 'Lubomierz'),
            c(40, 'DOLNOŚLĄSKIE', 'Lwówek Śląski'),
            c(41, 'DOLNOŚLĄSKIE', 'Mirsk'),
            c(42, 'DOLNOŚLĄSKIE', 'Wleń'),
            c(43, 'DOLNOŚLĄSKIE', 'Milicz'),
            c(44, 'DOLNOŚLĄSKIE', 'Oleśnica'),
            c(45, 'DOLNOŚLĄSKIE', 'Bierutów'),
            c(46, 'DOLNOŚLĄSKIE', 'Międzybórz'),
            c(47, 'DOLNOŚLĄSKIE', 'Syców'),
            c(48, 'DOLNOŚLĄSKIE', 'Twardogóra'),
            c(49, 'DOLNOŚLĄSKIE', 'Oława'),
            c(50, 'DOLNOŚLĄSKIE', 'Jelcz-Laskowice'),
            c(51, 'DOLNOŚLĄSKIE', 'Chocianów'),
            c(52, 'DOLNOŚLĄSKIE', 'Polkowice'),
            c(53, 'DOLNOŚLĄSKIE', 'Przemków'),
            c(54, 'DOLNOŚLĄSKIE', 'Strzelin'),
            c(55, 'DOLNOŚLĄSKIE', 'Wiązów'),
            c(56, 'DOLNOŚLĄSKIE', 'Środa Śląska'),
            c(57, 'DOLNOŚLĄSKIE', 'Świdnica'),
            c(58, 'DOLNOŚLĄSKIE', 'Świebodzice'),
            c(59, 'DOLNOŚLĄSKIE', 'Jaworzyna Śląska'),
            c(60, 'DOLNOŚLĄSKIE', 'Strzegom'),
            c(61, 'DOLNOŚLĄSKIE', 'Żarów'),
            c(62, 'DOLNOŚLĄSKIE', 'Oborniki Śląskie'),
            c(63, 'DOLNOŚLĄSKIE', 'Prusice'),
            c(64, 'DOLNOŚLĄSKIE', 'Trzebnica'),
            c(65, 'DOLNOŚLĄSKIE', 'Żmigród'),
            c(66, 'DOLNOŚLĄSKIE', 'Boguszów-Gorce'),
            c(67, 'DOLNOŚLĄSKIE', 'Jedlina-Zdrój'),
            c(68, 'DOLNOŚLĄSKIE', 'Szczawno-Zdrój'),
            c(69, 'DOLNOŚLĄSKIE', 'Głuszyca'),
            c(70, 'DOLNOŚLĄSKIE', 'Mieroszów'),
            c(71, 'DOLNOŚLĄSKIE', 'Brzeg Dolny'),
            c(72, 'DOLNOŚLĄSKIE', 'Wołów'),
            c(73, 'DOLNOŚLĄSKIE', 'Kąty Wrocławskie'),
            c(74, 'DOLNOŚLĄSKIE', 'Sobótka'),
            c(75, 'DOLNOŚLĄSKIE', 'Siechnice'),
            c(76, 'DOLNOŚLĄSKIE', 'Bardo'),
            c(77, 'DOLNOŚLĄSKIE', 'Ząbkowice Śląskie'),
            c(78, 'DOLNOŚLĄSKIE', 'Ziębice'),
            c(79, 'DOLNOŚLĄSKIE', 'Złoty Stok'),
            c(80, 'DOLNOŚLĄSKIE', 'Zawidów'),
            c(81, 'DOLNOŚLĄSKIE', 'Zgorzelec'),
            c(82, 'DOLNOŚLĄSKIE', 'Bogatynia'),
            c(83, 'DOLNOŚLĄSKIE', 'Pieńsk'),
            c(84, 'DOLNOŚLĄSKIE', 'Węgliniec'),
            c(85, 'DOLNOŚLĄSKIE', 'Wojcieszów'),
            c(86, 'DOLNOŚLĄSKIE', 'Złotoryja'),
            c(87, 'DOLNOŚLĄSKIE', 'Świerzawa'),
            c(88, 'DOLNOŚLĄSKIE', 'Jelenia Góra'),
            c(89, 'DOLNOŚLĄSKIE', 'Legnica'),
            c(90, 'DOLNOŚLĄSKIE', 'Wrocław'),
            c(91, 'DOLNOŚLĄSKIE', 'Wałbrzych'),
            c(92, 'KUJAWSKO-POMORSKIE', 'Aleksandrów Kujawski'),
            c(93, 'KUJAWSKO-POMORSKIE', 'Ciechocinek'),
            c(94, 'KUJAWSKO-POMORSKIE', 'Nieszawa'),
            c(95, 'KUJAWSKO-POMORSKIE', 'Brodnica'),
            c(96, 'KUJAWSKO-POMORSKIE', 'Górzno'),
            c(97, 'KUJAWSKO-POMORSKIE', 'Jabłonowo Pomorskie'),
            c(98, 'KUJAWSKO-POMORSKIE', 'Koronowo'),
            c(99, 'KUJAWSKO-POMORSKIE', 'Solec Kujawski'),
            c(100, 'KUJAWSKO-POMORSKIE', 'Chełmno'),
            c(101, 'KUJAWSKO-POMORSKIE', 'Golub-Dobrzyń'),
            c(102, 'KUJAWSKO-POMORSKIE', 'Kowalewo Pomorskie'),
            c(103, 'KUJAWSKO-POMORSKIE', 'Łasin'),
            c(104, 'KUJAWSKO-POMORSKIE', 'Radzyń Chełmiński'),
            c(105, 'KUJAWSKO-POMORSKIE', 'Inowrocław'),
            c(106, 'KUJAWSKO-POMORSKIE', 'Gniewkowo'),
            c(107, 'KUJAWSKO-POMORSKIE', 'Janikowo'),
            c(108, 'KUJAWSKO-POMORSKIE', 'Kruszwica'),
            c(109, 'KUJAWSKO-POMORSKIE', 'Pakość'),
            c(110, 'KUJAWSKO-POMORSKIE', 'Lipno'),
            c(111, 'KUJAWSKO-POMORSKIE', 'Dobrzyń nad Wisłą'),
            c(112, 'KUJAWSKO-POMORSKIE', 'Skępe'),
            c(113, 'KUJAWSKO-POMORSKIE', 'Mogilno'),
            c(114, 'KUJAWSKO-POMORSKIE', 'Strzelno'),
            c(115, 'KUJAWSKO-POMORSKIE', 'Kcynia'),
            c(116, 'KUJAWSKO-POMORSKIE', 'Mrocza'),
            c(117, 'KUJAWSKO-POMORSKIE', 'Nakło nad Notecią'),
            c(118, 'KUJAWSKO-POMORSKIE', 'Szubin'),
            c(119, 'KUJAWSKO-POMORSKIE', 'Radziejów'),
            c(120, 'KUJAWSKO-POMORSKIE', 'Piotrków Kujawski'),
            c(121, 'KUJAWSKO-POMORSKIE', 'Rypin'),
            c(122, 'KUJAWSKO-POMORSKIE', 'Kamień Krajeński'),
            c(123, 'KUJAWSKO-POMORSKIE', 'Sępólno Krajeńskie'),
            c(124, 'KUJAWSKO-POMORSKIE', 'Więcbork'),
            c(125, 'KUJAWSKO-POMORSKIE', 'Nowe'),
            c(126, 'KUJAWSKO-POMORSKIE', 'Świecie'),
            c(127, 'KUJAWSKO-POMORSKIE', 'Chełmża'),
            c(128, 'KUJAWSKO-POMORSKIE', 'Tuchola'),
            c(129, 'KUJAWSKO-POMORSKIE', 'Wąbrzeźno'),
            c(130, 'KUJAWSKO-POMORSKIE', 'Kowal'),
            c(131, 'KUJAWSKO-POMORSKIE', 'Brześć Kujawski'),
            c(132, 'KUJAWSKO-POMORSKIE', 'Chodecz'),
            c(133, 'KUJAWSKO-POMORSKIE', 'Izbica Kujawska'),
            c(134, 'KUJAWSKO-POMORSKIE', 'Lubień Kujawski'),
            c(135, 'KUJAWSKO-POMORSKIE', 'Lubraniec'),
            c(136, 'KUJAWSKO-POMORSKIE', 'Barcin'),
            c(137, 'KUJAWSKO-POMORSKIE', 'Janowiec Wielkopolski'),
            c(138, 'KUJAWSKO-POMORSKIE', 'Łabiszyn'),
            c(139, 'KUJAWSKO-POMORSKIE', 'Żnin'),
            c(140, 'KUJAWSKO-POMORSKIE', 'Bydgoszcz'),
            c(141, 'KUJAWSKO-POMORSKIE', 'Grudziądz'),
            c(142, 'KUJAWSKO-POMORSKIE', 'Toruń'),
            c(143, 'KUJAWSKO-POMORSKIE', 'Włocławek'),
            c(144, 'LUBELSKIE', 'Międzyrzec Podlaski'),
            c(145, 'LUBELSKIE', 'Terespol'),
            c(146, 'LUBELSKIE', 'Biłgoraj'),
            c(147, 'LUBELSKIE', 'Frampol'),
            c(148, 'LUBELSKIE', 'Józefów'),
            c(149, 'LUBELSKIE', 'Tarnogród'),
            c(150, 'LUBELSKIE', 'Rejowiec Fabryczny'),
            c(151, 'LUBELSKIE', 'Siedliszcze'),
            c(152, 'LUBELSKIE', 'Hrubieszów'),
            c(153, 'LUBELSKIE', 'Janów Lubelski'),
            c(154, 'LUBELSKIE', 'Modliborzyce'),
            c(155, 'LUBELSKIE', 'Krasnystaw'),
            c(156, 'LUBELSKIE', 'Kraśnik'),
            c(157, 'LUBELSKIE', 'Annopol'),
            c(158, 'LUBELSKIE', 'Urzędów'),
            c(159, 'LUBELSKIE', 'Lubartów'),
            c(160, 'LUBELSKIE', 'Kock'),
            c(161, 'LUBELSKIE', 'Ostrów Lubelski'),
            c(162, 'LUBELSKIE', 'Bełżyce'),
            c(163, 'LUBELSKIE', 'Bychawa'),
            c(164, 'LUBELSKIE', 'Łęczna'),
            c(165, 'LUBELSKIE', 'Łuków'),
            c(166, 'LUBELSKIE', 'Stoczek Łukowski'),
            c(167, 'LUBELSKIE', 'Opole Lubelskie'),
            c(168, 'LUBELSKIE', 'Poniatowa'),
            c(169, 'LUBELSKIE', 'Parczew'),
            c(170, 'LUBELSKIE', 'Puławy'),
            c(171, 'LUBELSKIE', 'Kazimierz Dolny'),
            c(172, 'LUBELSKIE', 'Nałęczów'),
            c(173, 'LUBELSKIE', 'Radzyń Podlaski'),
            c(174, 'LUBELSKIE', 'Dęblin'),
            c(175, 'LUBELSKIE', 'Ryki'),
            c(176, 'LUBELSKIE', 'Świdnik'),
            c(177, 'LUBELSKIE', 'Piaski'),
            c(178, 'LUBELSKIE', 'Tomaszów Lubelski'),
            c(179, 'LUBELSKIE', 'Lubycza Królewska'),
            c(180, 'LUBELSKIE', 'Łaszczów'),
            c(181, 'LUBELSKIE', 'Tyszowce'),
            c(182, 'LUBELSKIE', 'Włodawa'),
            c(183, 'LUBELSKIE', 'Krasnobród'),
            c(184, 'LUBELSKIE', 'Szczebrzeszyn'),
            c(185, 'LUBELSKIE', 'Zwierzyniec'),
            c(186, 'LUBELSKIE', 'Biała Podlaska'),
            c(187, 'LUBELSKIE', 'Chełm'),
            c(188, 'LUBELSKIE', 'Lublin'),
            c(189, 'LUBELSKIE', 'Zamość'),
            c(190, 'LUBUSKIE', 'Kostrzyn nad Odrą'),
            c(191, 'LUBUSKIE', 'Witnica'),
            c(192, 'LUBUSKIE', 'Gubin'),
            c(193, 'LUBUSKIE', 'Krosno Odrzańskie'),
            c(194, 'LUBUSKIE', 'Międzyrzecz'),
            c(195, 'LUBUSKIE', 'Skwierzyna'),
            c(196, 'LUBUSKIE', 'Trzciel'),
            c(197, 'LUBUSKIE', 'Nowa Sól'),
            c(198, 'LUBUSKIE', 'Bytom Odrzański'),
            c(199, 'LUBUSKIE', 'Kożuchów'),
            c(200, 'LUBUSKIE', 'Nowe Miasteczko'),
            c(201, 'LUBUSKIE', 'Cybinka'),
            c(202, 'LUBUSKIE', 'Ośno Lubuskie'),
            c(203, 'LUBUSKIE', 'Rzepin'),
            c(204, 'LUBUSKIE', 'Słubice'),
            c(205, 'LUBUSKIE', 'Dobiegniew'),
            c(206, 'LUBUSKIE', 'Drezdenko'),
            c(207, 'LUBUSKIE', 'Strzelce Krajeńskie'),
            c(208, 'LUBUSKIE', 'Lubniewice'),
            c(209, 'LUBUSKIE', 'Sulęcin'),
            c(210, 'LUBUSKIE', 'Torzym'),
            c(211, 'LUBUSKIE', 'Świebodzin'),
            c(212, 'LUBUSKIE', 'Zbąszynek'),
            c(213, 'LUBUSKIE', 'Babimost'),
            c(214, 'LUBUSKIE', 'Czerwieńsk'),
            c(215, 'LUBUSKIE', 'Kargowa'),
            c(216, 'LUBUSKIE', 'Nowogród Bobrzański'),
            c(217, 'LUBUSKIE', 'Sulechów'),
            c(218, 'LUBUSKIE', 'Gozdnica'),
            c(219, 'LUBUSKIE', 'Żagań'),
            c(220, 'LUBUSKIE', 'Iłowa'),
            c(221, 'LUBUSKIE', 'Małomice'),
            c(222, 'LUBUSKIE', 'Szprotawa'),
            c(223, 'LUBUSKIE', 'Łęknica'),
            c(224, 'LUBUSKIE', 'Żary'),
            c(225, 'LUBUSKIE', 'Jasień'),
            c(226, 'LUBUSKIE', 'Lubsko'),
            c(227, 'LUBUSKIE', 'Sława'),
            c(228, 'LUBUSKIE', 'Szlichtyngowa'),
            c(229, 'LUBUSKIE', 'Wschowa'),
            c(230, 'LUBUSKIE', 'Gorzów Wielkopolski'),
            c(231, 'LUBUSKIE', 'Zielona Góra'),
            c(232, 'ŁÓDZKIE', 'Bełchatów'),
            c(233, 'ŁÓDZKIE', 'Zelów'),
            c(234, 'ŁÓDZKIE', 'Kutno'),
            c(235, 'ŁÓDZKIE', 'Krośniewice'),
            c(236, 'ŁÓDZKIE', 'Żychlin'),
            c(237, 'ŁÓDZKIE', 'Łask'),
            c(238, 'ŁÓDZKIE', 'Łęczyca'),
            c(239, 'ŁÓDZKIE', 'Łowicz'),
            c(240, 'ŁÓDZKIE', 'Koluszki'),
            c(241, 'ŁÓDZKIE', 'Rzgów'),
            c(242, 'ŁÓDZKIE', 'Tuszyn'),
            c(243, 'ŁÓDZKIE', 'Drzewica'),
            c(244, 'ŁÓDZKIE', 'Opoczno'),
            c(245, 'ŁÓDZKIE', 'Konstantynów Łódzki'),
            c(246, 'ŁÓDZKIE', 'Pabianice'),
            c(247, 'ŁÓDZKIE', 'Działoszyn'),
            c(248, 'ŁÓDZKIE', 'Pajęczno'),
            c(249, 'ŁÓDZKIE', 'Sulejów'),
            c(250, 'ŁÓDZKIE', 'Wolbórz'),
            c(251, 'ŁÓDZKIE', 'Poddębice'),
            c(252, 'ŁÓDZKIE', 'Uniejów'),
            c(253, 'ŁÓDZKIE', 'Radomsko'),
            c(254, 'ŁÓDZKIE', 'Kamieńsk'),
            c(255, 'ŁÓDZKIE', 'Przedbórz'),
            c(256, 'ŁÓDZKIE', 'Rawa Mazowiecka'),
            c(257, 'ŁÓDZKIE', 'Biała Rawska'),
            c(258, 'ŁÓDZKIE', 'Sieradz'),
            c(259, 'ŁÓDZKIE', 'Błaszki'),
            c(260, 'ŁÓDZKIE', 'Warta'),
            c(261, 'ŁÓDZKIE', 'Złoczew'),
            c(262, 'ŁÓDZKIE', 'Tomaszów Mazowiecki'),
            c(263, 'ŁÓDZKIE', 'Wieluń'),
            c(264, 'ŁÓDZKIE', 'Wieruszów'),
            c(265, 'ŁÓDZKIE', 'Zduńska Wola'),
            c(266, 'ŁÓDZKIE', 'Szadek'),
            c(267, 'ŁÓDZKIE', 'Głowno'),
            c(268, 'ŁÓDZKIE', 'Ozorków'),
            c(269, 'ŁÓDZKIE', 'Zgierz'),
            c(270, 'ŁÓDZKIE', 'Aleksandrów Łódzki'),
            c(271, 'ŁÓDZKIE', 'Stryków'),
            c(272, 'ŁÓDZKIE', 'Brzeziny'),
            c(273, 'ŁÓDZKIE', 'Łódź'),
            c(274, 'ŁÓDZKIE', 'Piotrków Trybunalski'),
            c(275, 'ŁÓDZKIE', 'Skierniewice'),
            c(276, 'MAŁOPOLSKIE', 'Bochnia'),
            c(277, 'MAŁOPOLSKIE', 'Nowy Wiśnicz'),
            c(278, 'MAŁOPOLSKIE', 'Brzesko'),
            c(279, 'MAŁOPOLSKIE', 'Czchów'),
            c(280, 'MAŁOPOLSKIE', 'Alwernia'),
            c(281, 'MAŁOPOLSKIE', 'Chrzanów'),
            c(282, 'MAŁOPOLSKIE', 'Libiąż'),
            c(283, 'MAŁOPOLSKIE', 'Trzebinia'),
            c(284, 'MAŁOPOLSKIE', 'Dąbrowa Tarnowska'),
            c(285, 'MAŁOPOLSKIE', 'Szczucin'),
            c(286, 'MAŁOPOLSKIE', 'Gorlice'),
            c(287, 'MAŁOPOLSKIE', 'Biecz'),
            c(288, 'MAŁOPOLSKIE', 'Bobowa'),
            c(289, 'MAŁOPOLSKIE', 'Krzeszowice'),
            c(290, 'MAŁOPOLSKIE', 'Skała'),
            c(291, 'MAŁOPOLSKIE', 'Skawina'),
            c(292, 'MAŁOPOLSKIE', 'Słomniki'),
            c(293, 'MAŁOPOLSKIE', 'Świątniki Górne'),
            c(294, 'MAŁOPOLSKIE', 'Limanowa'),
            c(295, 'MAŁOPOLSKIE', 'Mszana Dolna'),
            c(296, 'MAŁOPOLSKIE', 'Miechów'),
            c(297, 'MAŁOPOLSKIE', 'Dobczyce'),
            c(298, 'MAŁOPOLSKIE', 'Myślenice'),
            c(299, 'MAŁOPOLSKIE', 'Sułkowice'),
            c(300, 'MAŁOPOLSKIE', 'Grybów'),
            c(301, 'MAŁOPOLSKIE', 'Krynica-Zdrój'),
            c(302, 'MAŁOPOLSKIE', 'Muszyna'),
            c(303, 'MAŁOPOLSKIE', 'Piwniczna-Zdrój'),
            c(304, 'MAŁOPOLSKIE', 'Stary Sącz'),
            c(305, 'MAŁOPOLSKIE', 'Nowy Targ'),
            c(306, 'MAŁOPOLSKIE', 'Szczawnica'),
            c(307, 'MAŁOPOLSKIE', 'Rabka-Zdrój'),
            c(308, 'MAŁOPOLSKIE', 'Bukowno'),
            c(309, 'MAŁOPOLSKIE', 'Olkusz'),
            c(310, 'MAŁOPOLSKIE', 'Wolbrom'),
            c(311, 'MAŁOPOLSKIE', 'Oświęcim'),
            c(312, 'MAŁOPOLSKIE', 'Brzeszcze'),
            c(313, 'MAŁOPOLSKIE', 'Chełmek'),
            c(314, 'MAŁOPOLSKIE', 'Kęty'),
            c(315, 'MAŁOPOLSKIE', 'Zator'),
            c(316, 'MAŁOPOLSKIE', 'Nowe Brzesko'),
            c(317, 'MAŁOPOLSKIE', 'Proszowice'),
            c(318, 'MAŁOPOLSKIE', 'Jordanów'),
            c(319, 'MAŁOPOLSKIE', 'Sucha Beskidzka'),
            c(320, 'MAŁOPOLSKIE', 'Maków Podhalański'),
            c(321, 'MAŁOPOLSKIE', 'Ciężkowice'),
            c(322, 'MAŁOPOLSKIE', 'Radłów'),
            c(323, 'MAŁOPOLSKIE', 'Ryglice'),
            c(324, 'MAŁOPOLSKIE', 'Tuchów'),
            c(325, 'MAŁOPOLSKIE', 'Wojnicz'),
            c(326, 'MAŁOPOLSKIE', 'Zakliczyn'),
            c(327, 'MAŁOPOLSKIE', 'Żabno'),
            c(328, 'MAŁOPOLSKIE', 'Zakopane'),
            c(329, 'MAŁOPOLSKIE', 'Andrychów'),
            c(330, 'MAŁOPOLSKIE', 'Kalwaria Zebrzydowska'),
            c(331, 'MAŁOPOLSKIE', 'Wadowice'),
            c(332, 'MAŁOPOLSKIE', 'Niepołomice'),
            c(333, 'MAŁOPOLSKIE', 'Wieliczka'),
            c(334, 'MAŁOPOLSKIE', 'Kraków'),
            c(335, 'MAŁOPOLSKIE', 'Nowy Sącz'),
            c(336, 'MAŁOPOLSKIE', 'Tarnów'),
            c(337, 'MAZOWIECKIE', 'Białobrzegi'),
            c(338, 'MAZOWIECKIE', 'Wyśmierzyce'),
            c(339, 'MAZOWIECKIE', 'Ciechanów'),
            c(340, 'MAZOWIECKIE', 'Glinojeck'),
            c(341, 'MAZOWIECKIE', 'Garwolin'),
            c(342, 'MAZOWIECKIE', 'Łaskarzew'),
            c(343, 'MAZOWIECKIE', 'Pilawa'),
            c(344, 'MAZOWIECKIE', 'Żelechów'),
            c(345, 'MAZOWIECKIE', 'Gostynin'),
            c(346, 'MAZOWIECKIE', 'Milanówek'),
            c(347, 'MAZOWIECKIE', 'Podkowa Leśna'),
            c(348, 'MAZOWIECKIE', 'Grodzisk Mazowiecki'),
            c(349, 'MAZOWIECKIE', 'Grójec'),
            c(350, 'MAZOWIECKIE', 'Mogielnica'),
            c(351, 'MAZOWIECKIE', 'Nowe Miasto nad Pilicą'),
            c(352, 'MAZOWIECKIE', 'Warka'),
            c(353, 'MAZOWIECKIE', 'Kozienice'),
            c(354, 'MAZOWIECKIE', 'Legionowo'),
            c(355, 'MAZOWIECKIE', 'Serock'),
            c(356, 'MAZOWIECKIE', 'Lipsko'),
            c(357, 'MAZOWIECKIE', 'Łosice'),
            c(358, 'MAZOWIECKIE', 'Maków Mazowiecki'),
            c(359, 'MAZOWIECKIE', 'Różan'),
            c(360, 'MAZOWIECKIE', 'Mińsk Mazowiecki'),
            c(361, 'MAZOWIECKIE', 'Halinów'),
            c(362, 'MAZOWIECKIE', 'Kałuszyn'),
            c(363, 'MAZOWIECKIE', 'Mrozy'),
            c(364, 'MAZOWIECKIE', 'Sulejówek'),
            c(365, 'MAZOWIECKIE', 'Mława'),
            c(366, 'MAZOWIECKIE', 'Nowy Dwór Mazowiecki'),
            c(367, 'MAZOWIECKIE', 'Nasielsk'),
            c(368, 'MAZOWIECKIE', 'Zakroczym'),
            c(369, 'MAZOWIECKIE', 'Myszyniec'),
            c(370, 'MAZOWIECKIE', 'Ostrów Mazowiecka'),
            c(371, 'MAZOWIECKIE', 'Brok'),
            c(372, 'MAZOWIECKIE', 'Józefów'),
            c(373, 'MAZOWIECKIE', 'Otwock'),
            c(374, 'MAZOWIECKIE', 'Karczew'),
            c(375, 'MAZOWIECKIE', 'Góra Kalwaria'),
            c(376, 'MAZOWIECKIE', 'Konstancin-Jeziorna'),
            c(377, 'MAZOWIECKIE', 'Piaseczno'),
            c(378, 'MAZOWIECKIE', 'Tarczyn'),
            c(379, 'MAZOWIECKIE', 'Drobin'),
            c(380, 'MAZOWIECKIE', 'Gąbin'),
            c(381, 'MAZOWIECKIE', 'Wyszogród'),
            c(382, 'MAZOWIECKIE', 'Płońsk'),
            c(383, 'MAZOWIECKIE', 'Raciąż'),
            c(384, 'MAZOWIECKIE', 'Piastów'),
            c(385, 'MAZOWIECKIE', 'Pruszków'),
            c(386, 'MAZOWIECKIE', 'Brwinów'),
            c(387, 'MAZOWIECKIE', 'Przasnysz'),
            c(388, 'MAZOWIECKIE', 'Chorzele'),
            c(389, 'MAZOWIECKIE', 'Przysucha'),
            c(390, 'MAZOWIECKIE', 'Pułtusk'),
            c(391, 'MAZOWIECKIE', 'Pionki'),
            c(392, 'MAZOWIECKIE', 'Iłża'),
            c(393, 'MAZOWIECKIE', 'Skaryszew'),
            c(394, 'MAZOWIECKIE', 'Mordy'),
            c(395, 'MAZOWIECKIE', 'Sierpc'),
            c(396, 'MAZOWIECKIE', 'Sochaczew'),
            c(397, 'MAZOWIECKIE', 'Sokołów Podlaski'),
            c(398, 'MAZOWIECKIE', 'Kosów Lacki'),
            c(399, 'MAZOWIECKIE', 'Szydłowiec'),
            c(400, 'MAZOWIECKIE', 'Błonie'),
            c(401, 'MAZOWIECKIE', 'Łomianki'),
            c(402, 'MAZOWIECKIE', 'Ożarów Mazowiecki'),
            c(403, 'MAZOWIECKIE', 'Węgrów'),
            c(404, 'MAZOWIECKIE', 'Łochów'),
            c(405, 'MAZOWIECKIE', 'Kobyłka'),
            c(406, 'MAZOWIECKIE', 'Marki'),
            c(407, 'MAZOWIECKIE', 'Ząbki'),
            c(408, 'MAZOWIECKIE', 'Zielonka'),
            c(409, 'MAZOWIECKIE', 'Radzymin'),
            c(410, 'MAZOWIECKIE', 'Tłuszcz'),
            c(411, 'MAZOWIECKIE', 'Wołomin'),
            c(412, 'MAZOWIECKIE', 'Wyszków'),
            c(413, 'MAZOWIECKIE', 'Zwoleń'),
            c(414, 'MAZOWIECKIE', 'Bieżuń'),
            c(415, 'MAZOWIECKIE', 'Żuromin'),
            c(416, 'MAZOWIECKIE', 'Żyrardów'),
            c(417, 'MAZOWIECKIE', 'Mszczonów'),
            c(418, 'MAZOWIECKIE', 'Ostrołęka'),
            c(419, 'MAZOWIECKIE', 'Płock'),
            c(420, 'MAZOWIECKIE', 'Radom'),
            c(421, 'MAZOWIECKIE', 'Siedlce'),
            c(422, 'OPOLSKIE', 'Brzeg'),
            c(423, 'OPOLSKIE', 'Grodków'),
            c(424, 'OPOLSKIE', 'Lewin Brzeski'),
            c(425, 'OPOLSKIE', 'Baborów'),
            c(426, 'OPOLSKIE', 'Głubczyce'),
            c(427, 'OPOLSKIE', 'Kietrz'),
            c(428, 'OPOLSKIE', 'Kędzierzyn-Koźle'),
            c(429, 'OPOLSKIE', 'Byczyna'),
            c(430, 'OPOLSKIE', 'Kluczbork'),
            c(431, 'OPOLSKIE', 'Wołczyn'),
            c(432, 'OPOLSKIE', 'Gogolin'),
            c(433, 'OPOLSKIE', 'Krapkowice'),
            c(434, 'OPOLSKIE', 'Zdzieszowice'),
            c(435, 'OPOLSKIE', 'Namysłów'),
            c(436, 'OPOLSKIE', 'Głuchołazy'),
            c(437, 'OPOLSKIE', 'Korfantów'),
            c(438, 'OPOLSKIE', 'Nysa'),
            c(439, 'OPOLSKIE', 'Otmuchów'),
            c(440, 'OPOLSKIE', 'Paczków'),
            c(441, 'OPOLSKIE', 'Dobrodzień'),
            c(442, 'OPOLSKIE', 'Gorzów Śląski'),
            c(443, 'OPOLSKIE', 'Olesno'),
            c(444, 'OPOLSKIE', 'Praszka'),
            c(445, 'OPOLSKIE', 'Niemodlin'),
            c(446, 'OPOLSKIE', 'Ozimek'),
            c(447, 'OPOLSKIE', 'Prószków'),
            c(448, 'OPOLSKIE', 'Biała'),
            c(449, 'OPOLSKIE', 'Głogówek'),
            c(450, 'OPOLSKIE', 'Prudnik'),
            c(451, 'OPOLSKIE', 'Kolonowskie'),
            c(452, 'OPOLSKIE', 'Leśnica'),
            c(453, 'OPOLSKIE', 'Strzelce Opolskie'),
            c(454, 'OPOLSKIE', 'Ujazd'),
            c(455, 'OPOLSKIE', 'Zawadzkie'),
            c(456, 'OPOLSKIE', 'Opole'),
            c(457, 'PODKARPACKIE', 'Ustrzyki Dolne'),
            c(458, 'PODKARPACKIE', 'Brzozów'),
            c(459, 'PODKARPACKIE', 'Dębica'),
            c(460, 'PODKARPACKIE', 'Brzostek'),
            c(461, 'PODKARPACKIE', 'Pilzno'),
            c(462, 'PODKARPACKIE', 'Jarosław'),
            c(463, 'PODKARPACKIE', 'Radymno'),
            c(464, 'PODKARPACKIE', 'Pruchnik'),
            c(465, 'PODKARPACKIE', 'Jasło'),
            c(466, 'PODKARPACKIE', 'Kołaczyce'),
            c(467, 'PODKARPACKIE', 'Kolbuszowa'),
            c(468, 'PODKARPACKIE', 'Dukla'),
            c(469, 'PODKARPACKIE', 'Iwonicz-Zdrój'),
            c(470, 'PODKARPACKIE', 'Jedlicze'),
            c(471, 'PODKARPACKIE', 'Rymanów'),
            c(472, 'PODKARPACKIE', 'Leżajsk'),
            c(473, 'PODKARPACKIE', 'Nowa Sarzyna'),
            c(474, 'PODKARPACKIE', 'Lubaczów'),
            c(475, 'PODKARPACKIE', 'Cieszanów'),
            c(476, 'PODKARPACKIE', 'Narol'),
            c(477, 'PODKARPACKIE', 'Oleszyce'),
            c(478, 'PODKARPACKIE', 'Łańcut'),
            c(479, 'PODKARPACKIE', 'Mielec'),
            c(480, 'PODKARPACKIE', 'Przecław'),
            c(481, 'PODKARPACKIE', 'Radomyśl Wielki'),
            c(482, 'PODKARPACKIE', 'Nisko'),
            c(483, 'PODKARPACKIE', 'Rudnik nad Sanem'),
            c(484, 'PODKARPACKIE', 'Ulanów'),
            c(485, 'PODKARPACKIE', 'Przeworsk'),
            c(486, 'PODKARPACKIE', 'Kańczuga'),
            c(487, 'PODKARPACKIE', 'Sieniawa'),
            c(488, 'PODKARPACKIE', 'Ropczyce'),
            c(489, 'PODKARPACKIE', 'Sędziszów Małopolski'),
            c(490, 'PODKARPACKIE', 'Dynów'),
            c(491, 'PODKARPACKIE', 'Błażowa'),
            c(492, 'PODKARPACKIE', 'Boguchwała'),
            c(493, 'PODKARPACKIE', 'Głogów Małopolski'),
            c(494, 'PODKARPACKIE', 'Sokołów Małopolski'),
            c(495, 'PODKARPACKIE', 'Tyczyn'),
            c(496, 'PODKARPACKIE', 'Sanok'),
            c(497, 'PODKARPACKIE', 'Zagórz'),
            c(498, 'PODKARPACKIE', 'Stalowa Wola'),
            c(499, 'PODKARPACKIE', 'Zaklików'),
            c(500, 'PODKARPACKIE', 'Strzyżów'),
            c(501, 'PODKARPACKIE', 'Baranów Sandomierski'),
            c(502, 'PODKARPACKIE', 'Nowa Dęba'),
            c(503, 'PODKARPACKIE', 'Lesko'),
            c(504, 'PODKARPACKIE', 'Krosno'),
            c(505, 'PODKARPACKIE', 'Przemyśl'),
            c(506, 'PODKARPACKIE', 'Rzeszów'),
            c(507, 'PODKARPACKIE', 'Tarnobrzeg'),
            c(508, 'PODLASKIE', 'Augustów'),
            c(509, 'PODLASKIE', 'Lipsk'),
            c(510, 'PODLASKIE', 'Choroszcz'),
            c(511, 'PODLASKIE', 'Czarna Białostocka'),
            c(512, 'PODLASKIE', 'Łapy'),
            c(513, 'PODLASKIE', 'Michałowo'),
            c(514, 'PODLASKIE', 'Supraśl'),
            c(515, 'PODLASKIE', 'Suraż'),
            c(516, 'PODLASKIE', 'Tykocin'),
            c(517, 'PODLASKIE', 'Wasilków'),
            c(518, 'PODLASKIE', 'Zabłudów'),
            c(519, 'PODLASKIE', 'Bielsk Podlaski'),
            c(520, 'PODLASKIE', 'Brańsk'),
            c(521, 'PODLASKIE', 'Grajewo'),
            c(522, 'PODLASKIE', 'Rajgród'),
            c(523, 'PODLASKIE', 'Szczuczyn'),
            c(524, 'PODLASKIE', 'Hajnówka'),
            c(525, 'PODLASKIE', 'Kleszczele'),
            c(526, 'PODLASKIE', 'Kolno'),
            c(527, 'PODLASKIE', 'Stawiski'),
            c(528, 'PODLASKIE', 'Jedwabne'),
            c(529, 'PODLASKIE', 'Nowogród'),
            c(530, 'PODLASKIE', 'Goniądz'),
            c(531, 'PODLASKIE', 'Knyszyn'),
            c(532, 'PODLASKIE', 'Mońki'),
            c(533, 'PODLASKIE', 'Sejny'),
            c(534, 'PODLASKIE', 'Siemiatycze'),
            c(535, 'PODLASKIE', 'Drohiczyn'),
            c(536, 'PODLASKIE', 'Dąbrowa Białostocka'),
            c(537, 'PODLASKIE', 'Krynki'),
            c(538, 'PODLASKIE', 'Sokółka'),
            c(539, 'PODLASKIE', 'Suchowola'),
            c(540, 'PODLASKIE', 'Wysokie Mazowieckie'),
            c(541, 'PODLASKIE', 'Ciechanowiec'),
            c(542, 'PODLASKIE', 'Czyżew'),
            c(543, 'PODLASKIE', 'Szepietowo'),
            c(544, 'PODLASKIE', 'Zambrów'),
            c(545, 'PODLASKIE', 'Białystok'),
            c(546, 'PODLASKIE', 'Łomża'),
            c(547, 'PODLASKIE', 'Suwałki'),
            c(548, 'POMORSKIE', 'Bytów'),
            c(549, 'POMORSKIE', 'Miastko'),
            c(550, 'POMORSKIE', 'Chojnice'),
            c(551, 'POMORSKIE', 'Brusy'),
            c(552, 'POMORSKIE', 'Czersk'),
            c(553, 'POMORSKIE', 'Człuchów'),
            c(554, 'POMORSKIE', 'Czarne'),
            c(555, 'POMORSKIE', 'Debrzno'),
            c(556, 'POMORSKIE', 'Pruszcz Gdański'),
            c(557, 'POMORSKIE', 'Kartuzy'),
            c(558, 'POMORSKIE', 'Żukowo'),
            c(559, 'POMORSKIE', 'Kościerzyna'),
            c(560, 'POMORSKIE', 'Kwidzyn'),
            c(561, 'POMORSKIE', 'Prabuty'),
            c(562, 'POMORSKIE', 'Lębork'),
            c(563, 'POMORSKIE', 'Łeba'),
            c(564, 'POMORSKIE', 'Malbork'),
            c(565, 'POMORSKIE', 'Nowy Staw'),
            c(566, 'POMORSKIE', 'Krynica Morska'),
            c(567, 'POMORSKIE', 'Nowy Dwór Gdański'),
            c(568, 'POMORSKIE', 'Hel'),
            c(569, 'POMORSKIE', 'Jastarnia'),
            c(570, 'POMORSKIE', 'Puck'),
            c(571, 'POMORSKIE', 'Władysławowo'),
            c(572, 'POMORSKIE', 'Ustka'),
            c(573, 'POMORSKIE', 'Kępice'),
            c(574, 'POMORSKIE', 'Czarna Woda'),
            c(575, 'POMORSKIE', 'Skórcz'),
            c(576, 'POMORSKIE', 'Starogard Gdański'),
            c(577, 'POMORSKIE', 'Skarszewy'),
            c(578, 'POMORSKIE', 'Tczew'),
            c(579, 'POMORSKIE', 'Gniew'),
            c(580, 'POMORSKIE', 'Pelplin'),
            c(581, 'POMORSKIE', 'Reda'),
            c(582, 'POMORSKIE', 'Rumia'),
            c(583, 'POMORSKIE', 'Wejherowo'),
            c(584, 'POMORSKIE', 'Dzierzgoń'),
            c(585, 'POMORSKIE', 'Sztum'),
            c(586, 'POMORSKIE', 'Gdańsk'),
            c(587, 'POMORSKIE', 'Gdynia'),
            c(588, 'POMORSKIE', 'Słupsk'),
            c(589, 'POMORSKIE', 'Sopot'),
            c(590, 'ŚLĄSKIE', 'Będzin'),
            c(591, 'ŚLĄSKIE', 'Czeladź'),
            c(592, 'ŚLĄSKIE', 'Wojkowice'),
            c(593, 'ŚLĄSKIE', 'Siewierz'),
            c(594, 'ŚLĄSKIE', 'Sławków'),
            c(595, 'ŚLĄSKIE', 'Szczyrk'),
            c(596, 'ŚLĄSKIE', 'Czechowice-Dziedzice'),
            c(597, 'ŚLĄSKIE', 'Wilamowice'),
            c(598, 'ŚLĄSKIE', 'Cieszyn'),
            c(599, 'ŚLĄSKIE', 'Ustroń'),
            c(600, 'ŚLĄSKIE', 'Wisła'),
            c(601, 'ŚLĄSKIE', 'Skoczów'),
            c(602, 'ŚLĄSKIE', 'Strumień'),
            c(603, 'ŚLĄSKIE', 'Blachownia'),
            c(604, 'ŚLĄSKIE', 'Koniecpol'),
            c(605, 'ŚLĄSKIE', 'Knurów'),
            c(606, 'ŚLĄSKIE', 'Pyskowice'),
            c(607, 'ŚLĄSKIE', 'Sośnicowice'),
            c(608, 'ŚLĄSKIE', 'Toszek'),
            c(609, 'ŚLĄSKIE', 'Kłobuck'),
            c(610, 'ŚLĄSKIE', 'Krzepice'),
            c(611, 'ŚLĄSKIE', 'Lubliniec'),
            c(612, 'ŚLĄSKIE', 'Woźniki'),
            c(613, 'ŚLĄSKIE', 'Łaziska Górne'),
            c(614, 'ŚLĄSKIE', 'Mikołów'),
            c(615, 'ŚLĄSKIE', 'Orzesze'),
            c(616, 'ŚLĄSKIE', 'Myszków'),
            c(617, 'ŚLĄSKIE', 'Koziegłowy'),
            c(618, 'ŚLĄSKIE', 'Żarki'),
            c(619, 'ŚLĄSKIE', 'Pszczyna'),
            c(620, 'ŚLĄSKIE', 'Racibórz'),
            c(621, 'ŚLĄSKIE', 'Krzanowice'),
            c(622, 'ŚLĄSKIE', 'Kuźnia Raciborska'),
            c(623, 'ŚLĄSKIE', 'Czerwionka-Leszczyny'),
            c(624, 'ŚLĄSKIE', 'Kalety'),
            c(625, 'ŚLĄSKIE', 'Miasteczko Śląskie'),
            c(626, 'ŚLĄSKIE', 'Radzionków'),
            c(627, 'ŚLĄSKIE', 'Tarnowskie Góry'),
            c(628, 'ŚLĄSKIE', 'Bieruń'),
            c(629, 'ŚLĄSKIE', 'Imielin'),
            c(630, 'ŚLĄSKIE', 'Lędziny'),
            c(631, 'ŚLĄSKIE', 'Pszów'),
            c(632, 'ŚLĄSKIE', 'Radlin'),
            c(633, 'ŚLĄSKIE', 'Rydułtowy'),
            c(634, 'ŚLĄSKIE', 'Wodzisław Śląski'),
            c(635, 'ŚLĄSKIE', 'Poręba'),
            c(636, 'ŚLĄSKIE', 'Zawiercie'),
            c(637, 'ŚLĄSKIE', 'Łazy'),
            c(638, 'ŚLĄSKIE', 'Ogrodzieniec'),
            c(639, 'ŚLĄSKIE', 'Pilica'),
            c(640, 'ŚLĄSKIE', 'Szczekociny'),
            c(641, 'ŚLĄSKIE', 'Żywiec'),
            c(642, 'ŚLĄSKIE', 'Bielsko-Biała'),
            c(643, 'ŚLĄSKIE', 'Bytom'),
            c(644, 'ŚLĄSKIE', 'Chorzów'),
            c(645, 'ŚLĄSKIE', 'Częstochowa'),
            c(646, 'ŚLĄSKIE', 'Dąbrowa Górnicza'),
            c(647, 'ŚLĄSKIE', 'Gliwice'),
            c(648, 'ŚLĄSKIE', 'Jastrzębie-Zdrój'),
            c(649, 'ŚLĄSKIE', 'Jaworzno'),
            c(650, 'ŚLĄSKIE', 'Katowice'),
            c(651, 'ŚLĄSKIE', 'Mysłowice'),
            c(652, 'ŚLĄSKIE', 'Piekary Śląskie'),
            c(653, 'ŚLĄSKIE', 'Ruda Śląska'),
            c(654, 'ŚLĄSKIE', 'Rybnik'),
            c(655, 'ŚLĄSKIE', 'Siemianowice Śląskie'),
            c(656, 'ŚLĄSKIE', 'Sosnowiec'),
            c(657, 'ŚLĄSKIE', 'Świętochłowice'),
            c(658, 'ŚLĄSKIE', 'Tychy'),
            c(659, 'ŚLĄSKIE', 'Zabrze'),
            c(660, 'ŚLĄSKIE', 'Żory'),
            c(661, 'ŚWIĘTOKRZYSKIE', 'Busko-Zdrój'),
            c(662, 'ŚWIĘTOKRZYSKIE', 'Stopnica'),
            c(663, 'ŚWIĘTOKRZYSKIE', 'Jędrzejów'),
            c(664, 'ŚWIĘTOKRZYSKIE', 'Małogoszcz'),
            c(665, 'ŚWIĘTOKRZYSKIE', 'Sędziszów'),
            c(666, 'ŚWIĘTOKRZYSKIE', 'Kazimierza Wielka'),
            c(667, 'ŚWIĘTOKRZYSKIE', 'Skalbmierz'),
            c(668, 'ŚWIĘTOKRZYSKIE', 'Bodzentyn'),
            c(669, 'ŚWIĘTOKRZYSKIE', 'Chęciny'),
            c(670, 'ŚWIĘTOKRZYSKIE', 'Chmielnik'),
            c(671, 'ŚWIĘTOKRZYSKIE', 'Daleszyce'),
            c(672, 'ŚWIĘTOKRZYSKIE', 'Końskie'),
            c(673, 'ŚWIĘTOKRZYSKIE', 'Stąporków'),
            c(674, 'ŚWIĘTOKRZYSKIE', 'Opatów'),
            c(675, 'ŚWIĘTOKRZYSKIE', 'Ożarów'),
            c(676, 'ŚWIĘTOKRZYSKIE', 'Ostrowiec Świętokrzyski'),
            c(677, 'ŚWIĘTOKRZYSKIE', 'Ćmielów'),
            c(678, 'ŚWIĘTOKRZYSKIE', 'Kunów'),
            c(679, 'ŚWIĘTOKRZYSKIE', 'Działoszyce'),
            c(680, 'ŚWIĘTOKRZYSKIE', 'Pińczów'),
            c(681, 'ŚWIĘTOKRZYSKIE', 'Sandomierz'),
            c(682, 'ŚWIĘTOKRZYSKIE', 'Koprzywnica'),
            c(683, 'ŚWIĘTOKRZYSKIE', 'Zawichost'),
            c(684, 'ŚWIĘTOKRZYSKIE', 'Skarżysko-Kamienna'),
            c(685, 'ŚWIĘTOKRZYSKIE', 'Suchedniów'),
            c(686, 'ŚWIĘTOKRZYSKIE', 'Starachowice'),
            c(687, 'ŚWIĘTOKRZYSKIE', 'Wąchock'),
            c(688, 'ŚWIĘTOKRZYSKIE', 'Osiek'),
            c(689, 'ŚWIĘTOKRZYSKIE', 'Połaniec'),
            c(690, 'ŚWIĘTOKRZYSKIE', 'Staszów'),
            c(691, 'ŚWIĘTOKRZYSKIE', 'Włoszczowa'),
            c(692, 'ŚWIĘTOKRZYSKIE', 'Kielce'),
            c(693, 'WARMIŃSKO-MAZURSKIE', 'Bartoszyce'),
            c(694, 'WARMIŃSKO-MAZURSKIE', 'Górowo Iławeckie'),
            c(695, 'WARMIŃSKO-MAZURSKIE', 'Bisztynek'),
            c(696, 'WARMIŃSKO-MAZURSKIE', 'Sępopol'),
            c(697, 'WARMIŃSKO-MAZURSKIE', 'Braniewo'),
            c(698, 'WARMIŃSKO-MAZURSKIE', 'Frombork'),
            c(699, 'WARMIŃSKO-MAZURSKIE', 'Pieniężno'),
            c(700, 'WARMIŃSKO-MAZURSKIE', 'Działdowo'),
            c(701, 'WARMIŃSKO-MAZURSKIE', 'Lidzbark'),
            c(702, 'WARMIŃSKO-MAZURSKIE', 'Młynary'),
            c(703, 'WARMIŃSKO-MAZURSKIE', 'Pasłęk'),
            c(704, 'WARMIŃSKO-MAZURSKIE', 'Tolkmicko'),
            c(705, 'WARMIŃSKO-MAZURSKIE', 'Ełk'),
            c(706, 'WARMIŃSKO-MAZURSKIE', 'Giżycko'),
            c(707, 'WARMIŃSKO-MAZURSKIE', 'Ryn'),
            c(708, 'WARMIŃSKO-MAZURSKIE', 'Iława'),
            c(709, 'WARMIŃSKO-MAZURSKIE', 'Lubawa'),
            c(710, 'WARMIŃSKO-MAZURSKIE', 'Kisielice'),
            c(711, 'WARMIŃSKO-MAZURSKIE', 'Susz'),
            c(712, 'WARMIŃSKO-MAZURSKIE', 'Zalewo'),
            c(713, 'WARMIŃSKO-MAZURSKIE', 'Kętrzyn'),
            c(714, 'WARMIŃSKO-MAZURSKIE', 'Korsze'),
            c(715, 'WARMIŃSKO-MAZURSKIE', 'Reszel'),
            c(716, 'WARMIŃSKO-MAZURSKIE', 'Lidzbark Warmiński'),
            c(717, 'WARMIŃSKO-MAZURSKIE', 'Orneta'),
            c(718, 'WARMIŃSKO-MAZURSKIE', 'Mrągowo'),
            c(719, 'WARMIŃSKO-MAZURSKIE', 'Mikołajki'),
            c(720, 'WARMIŃSKO-MAZURSKIE', 'Nidzica'),
            c(721, 'WARMIŃSKO-MAZURSKIE', 'Nowe Miasto Lubawskie'),
            c(722, 'WARMIŃSKO-MAZURSKIE', 'Olecko'),
            c(723, 'WARMIŃSKO-MAZURSKIE', 'Barczewo'),
            c(724, 'WARMIŃSKO-MAZURSKIE', 'Biskupiec'),
            c(725, 'WARMIŃSKO-MAZURSKIE', 'Dobre Miasto'),
            c(726, 'WARMIŃSKO-MAZURSKIE', 'Jeziorany'),
            c(727, 'WARMIŃSKO-MAZURSKIE', 'Olsztynek'),
            c(728, 'WARMIŃSKO-MAZURSKIE', 'Ostróda'),
            c(729, 'WARMIŃSKO-MAZURSKIE', 'Miłakowo'),
            c(730, 'WARMIŃSKO-MAZURSKIE', 'Miłomłyn'),
            c(731, 'WARMIŃSKO-MAZURSKIE', 'Morąg'),
            c(732, 'WARMIŃSKO-MAZURSKIE', 'Biała Piska'),
            c(733, 'WARMIŃSKO-MAZURSKIE', 'Orzysz'),
            c(734, 'WARMIŃSKO-MAZURSKIE', 'Pisz'),
            c(735, 'WARMIŃSKO-MAZURSKIE', 'Ruciane-Nida'),
            c(736, 'WARMIŃSKO-MAZURSKIE', 'Szczytno'),
            c(737, 'WARMIŃSKO-MAZURSKIE', 'Pasym'),
            c(738, 'WARMIŃSKO-MAZURSKIE', 'Gołdap'),
            c(739, 'WARMIŃSKO-MAZURSKIE', 'Węgorzewo'),
            c(740, 'WARMIŃSKO-MAZURSKIE', 'Elbląg'),
            c(741, 'WARMIŃSKO-MAZURSKIE', 'Olsztyn'),
            c(742, 'WIELKOPOLSKIE', 'Chodzież'),
            c(743, 'WIELKOPOLSKIE', 'Margonin'),
            c(744, 'WIELKOPOLSKIE', 'Szamocin'),
            c(745, 'WIELKOPOLSKIE', 'Czarnków'),
            c(746, 'WIELKOPOLSKIE', 'Krzyż Wielkopolski'),
            c(747, 'WIELKOPOLSKIE', 'Trzcianka'),
            c(748, 'WIELKOPOLSKIE', 'Wieleń'),
            c(749, 'WIELKOPOLSKIE', 'Gniezno'),
            c(750, 'WIELKOPOLSKIE', 'Czerniejewo'),
            c(751, 'WIELKOPOLSKIE', 'Kłecko'),
            c(752, 'WIELKOPOLSKIE', 'Trzemeszno'),
            c(753, 'WIELKOPOLSKIE', 'Witkowo'),
            c(754, 'WIELKOPOLSKIE', 'Borek Wielkopolski'),
            c(755, 'WIELKOPOLSKIE', 'Gostyń'),
            c(756, 'WIELKOPOLSKIE', 'Krobia'),
            c(757, 'WIELKOPOLSKIE', 'Pogorzela'),
            c(758, 'WIELKOPOLSKIE', 'Poniec'),
            c(759, 'WIELKOPOLSKIE', 'Grodzisk Wielkopolski'),
            c(760, 'WIELKOPOLSKIE', 'Rakoniewice'),
            c(761, 'WIELKOPOLSKIE', 'Wielichowo'),
            c(762, 'WIELKOPOLSKIE', 'Jaraczewo'),
            c(763, 'WIELKOPOLSKIE', 'Jarocin'),
            c(764, 'WIELKOPOLSKIE', 'Żerków'),
            c(765, 'WIELKOPOLSKIE', 'Stawiszyn'),
            c(766, 'WIELKOPOLSKIE', 'Kępno'),
            c(767, 'WIELKOPOLSKIE', 'Koło'),
            c(768, 'WIELKOPOLSKIE', 'Dąbie'),
            c(769, 'WIELKOPOLSKIE', 'Kłodawa'),
            c(770, 'WIELKOPOLSKIE', 'Przedecz'),
            c(771, 'WIELKOPOLSKIE', 'Golina'),
            c(772, 'WIELKOPOLSKIE', 'Kleczew'),
            c(773, 'WIELKOPOLSKIE', 'Rychwał'),
            c(774, 'WIELKOPOLSKIE', 'Sompolno'),
            c(775, 'WIELKOPOLSKIE', 'Ślesin'),
            c(776, 'WIELKOPOLSKIE', 'Kościan'),
            c(777, 'WIELKOPOLSKIE', 'Czempiń'),
            c(778, 'WIELKOPOLSKIE', 'Krzywiń'),
            c(779, 'WIELKOPOLSKIE', 'Śmigiel'),
            c(780, 'WIELKOPOLSKIE', 'Sulmierzyce'),
            c(781, 'WIELKOPOLSKIE', 'Kobylin'),
            c(782, 'WIELKOPOLSKIE', 'Koźmin Wielkopolski'),
            c(783, 'WIELKOPOLSKIE', 'Krotoszyn'),
            c(784, 'WIELKOPOLSKIE', 'Zduny'),
            c(785, 'WIELKOPOLSKIE', 'Osieczna'),
            c(786, 'WIELKOPOLSKIE', 'Rydzyna'),
            c(787, 'WIELKOPOLSKIE', 'Międzychód'),
            c(788, 'WIELKOPOLSKIE', 'Sieraków'),
            c(789, 'WIELKOPOLSKIE', 'Lwówek'),
            c(790, 'WIELKOPOLSKIE', 'Nowy Tomyśl'),
            c(791, 'WIELKOPOLSKIE', 'Opalenica'),
            c(792, 'WIELKOPOLSKIE', 'Zbąszyń'),
            c(793, 'WIELKOPOLSKIE', 'Oborniki'),
            c(794, 'WIELKOPOLSKIE', 'Rogoźno'),
            c(795, 'WIELKOPOLSKIE', 'Ostrów Wielkopolski'),
            c(796, 'WIELKOPOLSKIE', 'Nowe Skalmierzyce'),
            c(797, 'WIELKOPOLSKIE', 'Odolanów'),
            c(798, 'WIELKOPOLSKIE', 'Raszków'),
            c(799, 'WIELKOPOLSKIE', 'Grabów nad Prosną'),
            c(800, 'WIELKOPOLSKIE', 'Mikstat'),
            c(801, 'WIELKOPOLSKIE', 'Ostrzeszów'),
            c(802, 'WIELKOPOLSKIE', 'Piła'),
            c(803, 'WIELKOPOLSKIE', 'Łobżenica'),
            c(804, 'WIELKOPOLSKIE', 'Ujście'),
            c(805, 'WIELKOPOLSKIE', 'Wyrzysk'),
            c(806, 'WIELKOPOLSKIE', 'Wysoka'),
            c(807, 'WIELKOPOLSKIE', 'Chocz'),
            c(808, 'WIELKOPOLSKIE', 'Dobrzyca'),
            c(809, 'WIELKOPOLSKIE', 'Pleszew'),
            c(810, 'WIELKOPOLSKIE', 'Luboń'),
            c(811, 'WIELKOPOLSKIE', 'Puszczykowo'),
            c(812, 'WIELKOPOLSKIE', 'Buk'),
            c(813, 'WIELKOPOLSKIE', 'Kostrzyn'),
            c(814, 'WIELKOPOLSKIE', 'Kórnik'),
            c(815, 'WIELKOPOLSKIE', 'Mosina'),
            c(816, 'WIELKOPOLSKIE', 'Murowana Goślina'),
            c(817, 'WIELKOPOLSKIE', 'Pobiedziska'),
            c(818, 'WIELKOPOLSKIE', 'Stęszew'),
            c(819, 'WIELKOPOLSKIE', 'Swarzędz'),
            c(820, 'WIELKOPOLSKIE', 'Bojanowo'),
            c(821, 'WIELKOPOLSKIE', 'Jutrosin'),
            c(822, 'WIELKOPOLSKIE', 'Miejska Górka'),
            c(823, 'WIELKOPOLSKIE', 'Rawicz'),
            c(824, 'WIELKOPOLSKIE', 'Słupca'),
            c(825, 'WIELKOPOLSKIE', 'Zagórów'),
            c(826, 'WIELKOPOLSKIE', 'Obrzycko'),
            c(827, 'WIELKOPOLSKIE', 'Ostroróg'),
            c(828, 'WIELKOPOLSKIE', 'Pniewy'),
            c(829, 'WIELKOPOLSKIE', 'Szamotuły'),
            c(830, 'WIELKOPOLSKIE', 'Wronki'),
            c(831, 'WIELKOPOLSKIE', 'Środa Wielkopolska'),
            c(832, 'WIELKOPOLSKIE', 'Dolsk'),
            c(833, 'WIELKOPOLSKIE', 'Książ Wielkopolski'),
            c(834, 'WIELKOPOLSKIE', 'Śrem'),
            c(835, 'WIELKOPOLSKIE', 'Turek'),
            c(836, 'WIELKOPOLSKIE', 'Dobra'),
            c(837, 'WIELKOPOLSKIE', 'Tuliszków'),
            c(838, 'WIELKOPOLSKIE', 'Wągrowiec'),
            c(839, 'WIELKOPOLSKIE', 'Gołańcz'),
            c(840, 'WIELKOPOLSKIE', 'Skoki'),
            c(841, 'WIELKOPOLSKIE', 'Wolsztyn'),
            c(842, 'WIELKOPOLSKIE', 'Miłosław'),
            c(843, 'WIELKOPOLSKIE', 'Nekla'),
            c(844, 'WIELKOPOLSKIE', 'Pyzdry'),
            c(845, 'WIELKOPOLSKIE', 'Września'),
            c(846, 'WIELKOPOLSKIE', 'Złotów'),
            c(847, 'WIELKOPOLSKIE', 'Jastrowie'),
            c(848, 'WIELKOPOLSKIE', 'Krajenka'),
            c(849, 'WIELKOPOLSKIE', 'Okonek'),
            c(850, 'WIELKOPOLSKIE', 'Kalisz'),
            c(851, 'WIELKOPOLSKIE', 'Konin'),
            c(852, 'WIELKOPOLSKIE', 'Leszno'),
            c(853, 'WIELKOPOLSKIE', 'Poznań'),
            c(854, 'ZACHODNIOPOMORSKIE', 'Białogard'),
            c(855, 'ZACHODNIOPOMORSKIE', 'Karlino'),
            c(856, 'ZACHODNIOPOMORSKIE', 'Tychowo'),
            c(857, 'ZACHODNIOPOMORSKIE', 'Choszczno'),
            c(858, 'ZACHODNIOPOMORSKIE', 'Drawno'),
            c(859, 'ZACHODNIOPOMORSKIE', 'Pełczyce'),
            c(860, 'ZACHODNIOPOMORSKIE', 'Recz'),
            c(861, 'ZACHODNIOPOMORSKIE', 'Czaplinek'),
            c(862, 'ZACHODNIOPOMORSKIE', 'Drawsko Pomorskie'),
            c(863, 'ZACHODNIOPOMORSKIE', 'Kalisz Pomorski'),
            c(864, 'ZACHODNIOPOMORSKIE', 'Złocieniec'),
            c(865, 'ZACHODNIOPOMORSKIE', 'Goleniów'),
            c(866, 'ZACHODNIOPOMORSKIE', 'Maszewo'),
            c(867, 'ZACHODNIOPOMORSKIE', 'Nowogard'),
            c(868, 'ZACHODNIOPOMORSKIE', 'Stepnica'),
            c(869, 'ZACHODNIOPOMORSKIE', 'Gryfice'),
            c(870, 'ZACHODNIOPOMORSKIE', 'Płoty'),
            c(871, 'ZACHODNIOPOMORSKIE', 'Trzebiatów'),
            c(872, 'ZACHODNIOPOMORSKIE', 'Cedynia'),
            c(873, 'ZACHODNIOPOMORSKIE', 'Chojna'),
            c(874, 'ZACHODNIOPOMORSKIE', 'Gryfino'),
            c(875, 'ZACHODNIOPOMORSKIE', 'Mieszkowice'),
            c(876, 'ZACHODNIOPOMORSKIE', 'Moryń'),
            c(877, 'ZACHODNIOPOMORSKIE', 'Trzcińsko-Zdrój'),
            c(878, 'ZACHODNIOPOMORSKIE', 'Dziwnów'),
            c(879, 'ZACHODNIOPOMORSKIE', 'Golczewo'),
            c(880, 'ZACHODNIOPOMORSKIE', 'Kamień Pomorski'),
            c(881, 'ZACHODNIOPOMORSKIE', 'Międzyzdroje'),
            c(882, 'ZACHODNIOPOMORSKIE', 'Wolin'),
            c(883, 'ZACHODNIOPOMORSKIE', 'Kołobrzeg'),
            c(884, 'ZACHODNIOPOMORSKIE', 'Gościno'),
            c(885, 'ZACHODNIOPOMORSKIE', 'Bobolice'),
            c(886, 'ZACHODNIOPOMORSKIE', 'Polanów'),
            c(887, 'ZACHODNIOPOMORSKIE', 'Sianów'),
            c(888, 'ZACHODNIOPOMORSKIE', 'Barlinek'),
            c(889, 'ZACHODNIOPOMORSKIE', 'Dębno'),
            c(890, 'ZACHODNIOPOMORSKIE', 'Myślibórz'),
            c(891, 'ZACHODNIOPOMORSKIE', 'Nowe Warpno'),
            c(892, 'ZACHODNIOPOMORSKIE', 'Police'),
            c(893, 'ZACHODNIOPOMORSKIE', 'Lipiany'),
            c(894, 'ZACHODNIOPOMORSKIE', 'Pyrzyce'),
            c(895, 'ZACHODNIOPOMORSKIE', 'Darłowo'),
            c(896, 'ZACHODNIOPOMORSKIE', 'Sławno'),
            c(897, 'ZACHODNIOPOMORSKIE', 'Stargard'),
            c(898, 'ZACHODNIOPOMORSKIE', 'Chociwel'),
            c(899, 'ZACHODNIOPOMORSKIE', 'Dobrzany'),
            c(900, 'ZACHODNIOPOMORSKIE', 'Ińsko'),
            c(901, 'ZACHODNIOPOMORSKIE', 'Suchań'),
            c(902, 'ZACHODNIOPOMORSKIE', 'Szczecinek'),
            c(903, 'ZACHODNIOPOMORSKIE', 'Barwice'),
            c(904, 'ZACHODNIOPOMORSKIE', 'Biały Bór'),
            c(905, 'ZACHODNIOPOMORSKIE', 'Borne Sulinowo'),
            c(906, 'ZACHODNIOPOMORSKIE', 'Świdwin'),
            c(907, 'ZACHODNIOPOMORSKIE', 'Połczyn-Zdrój'),
            c(908, 'ZACHODNIOPOMORSKIE', 'Wałcz'),
            c(909, 'ZACHODNIOPOMORSKIE', 'Człopa'),
            c(910, 'ZACHODNIOPOMORSKIE', 'Mirosławiec'),
            c(911, 'ZACHODNIOPOMORSKIE', 'Tuczno'),
            c(912, 'ZACHODNIOPOMORSKIE', 'Dobra'),
            c(913, 'ZACHODNIOPOMORSKIE', 'Łobez'),
            c(914, 'ZACHODNIOPOMORSKIE', 'Resko'),
            c(915, 'ZACHODNIOPOMORSKIE', 'Węgorzyno'),
            c(916, 'ZACHODNIOPOMORSKIE', 'Koszalin'),
            c(917, 'ZACHODNIOPOMORSKIE', 'Szczecin'),
            c(918, 'ZACHODNIOPOMORSKIE', 'Świnoujście'))
